cask_args appdir: "/Applications"

tap "argon/mas"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "railwaycat/emacsmacport"
tap "rcmdnk/file"
tap "sanemat/font"
tap "shopify/shopify"
brew "ansible"
brew "autoconf"
brew "autojump"
brew "automake"
brew "aws-elasticbeanstalk"
brew "awscli"
brew "bat"
brew "bluetoothconnector"
brew "cairo"
brew "cmake"
brew "composer", link: false
brew "coreutils"
brew "ctags"
brew "curl"
brew "docker-compose"
brew "endurance"
brew "gobject-introspection"
brew "fontforge"
brew "git"
brew "go"
brew "hub"
brew "jq"
brew "lv"
brew "mas"
brew "mysql"
brew "nkf"
brew "nodebrew"
brew "pyenv"
brew "python@3.8"
brew "ruby-build"
brew "rbenv"
brew "redis"
brew "ruby"
brew "the_silver_searcher"
brew "tig"
brew "tree"
brew "vim"
brew "watch"
brew "wget"
brew "yarn"
brew "zlib"
brew "zplug"
brew "zsh"
brew "heroku/brew/heroku"
brew "rcmdnk/file/brew-file"
brew "shopify/shopify/themekit"
cask "alfred"
cask "alternote"
cask "appcleaner"
cask "authy"
cask "bartender"
cask "bettertouchtool"
cask "biscuit"
cask "coteditor"
cask "dash"
cask "discord"
cask "docker"
cask "dropbox"
cask "duet"
cask "figma"
cask "firefox"
cask "flux"
cask "fuwari"
cask "google-cloud-sdk"
cask "google-japanese-ime"
cask "grandperspective"
cask "gyazo"
cask "hyperswitch"
cask "iterm2"
cask "jasper"
cask "java6"
cask "karabiner-elements"
cask "kindle"
cask "licecap"
cask "mysqlworkbench"
cask "ngrok"
cask "quik"
cask "sequel-pro"
cask "sketch"
cask "skitch"
cask "slack"
cask "tg-pro"
cask "the-unarchiver"
cask "tripmode"
cask "turbo-boost-switcher"
cask "visual-studio-code"
cask "zoom"
mas "1Password 7", id: 1333542190
mas "Amphetamine", id: 937984704
mas "com.alice.mac.GetPlainText", id: 508368068
mas "com.rockysandstudio.FreeMemory", id: 460931672
mas "Day One", id: 1055511498
mas "Deckset", id: 847496013
mas "Final Cut Pro", id: 424389933
mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "Irvue", id: 1039633667
mas "Keynote", id: 409183694
mas "LINE", id: 539883307
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Paste", id: 967805235
mas "Todoist", id: 585829637
mas "TweetDeck", id: 485812721
mas "Xcode", id: 497799835
mas "Yoink", id: 457622435
