tap "1password/tap"
tap "adoptopenjdk/openjdk"
tap "argon/mas"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask-versions"
tap "homebrew/services"
tap "ngrok/ngrok"
tap "railwaycat/emacsmacport"
tap "rcmdnk/file"
tap "sanemat/font"
tap "stripe/stripe-cli"

# Formulae
brew "abseil"
brew "act"
brew "asdf"
brew "autoconf"
brew "autojump"
brew "automake"
brew "aws-elasticbeanstalk"
brew "awscli"
brew "bat"
brew "brew-file"
brew "cairo"
brew "cmake"
brew "composer"
brew "coreutils"
brew "curl"
brew "docker-compose"
brew "ffmpeg"
brew "flyctl"
brew "gawk"
brew "gh"
brew "ghq"
brew "git-delta"
brew "gnupg"
brew "go"
brew "gobject-introspection"
brew "graphviz"
brew "harfbuzz"
brew "heroku"
brew "hub"
brew "imagemagick"
brew "jpeg-xl"
brew "jq"
brew "libfido2"
brew "libpq"
brew "librsvg"
brew "lv"
brew "marp-cli"
brew "mas"
brew "mkcert"
brew "mysql"
brew "mysql@8.0"
brew "nkf"
brew "node"
brew "node@16"
brew "openjdk"
brew "openjdk@11"
brew "openjdk@17"
brew "pango"
brew "peco"
brew "postgresql@14"
brew "python@3.11"
brew "python@3.12"
brew "redis"
brew "ruby"
brew "stripe"
brew "tfenv"
brew "the_silver_searcher"
brew "tig"
brew "tree"
brew "uv"
brew "vim"
brew "volta"
brew "watch"
brew "wget"
brew "yarn"
brew "zplug"
brew "zsh"

# Casks
cask "alt-tab"
cask "appcleaner"
cask "authy"
cask "bartender"
cask "bettertouchtool"
cask "cleanshot"
cask "coteditor"
cask "dash"
cask "discord"
cask "docker"
cask "dropbox"
cask "duet"
cask "figma"
cask "firefox"
cask "focus"
cask "font-ipaexfont"
cask "gather"
cask "google-cloud-sdk"
cask "google-japanese-ime"
cask "grandperspective"
cask "graphql-playground"
cask "gyazo"
cask "iterm2"
cask "java6"
cask "karabiner-elements"
cask "kindle"
cask "mysqlworkbench"
cask "ngrok"
cask "orbstack"
cask "raycast"
cask "sequel-pro"
cask "skitch"
cask "slack"
cask "the-unarchiver"
cask "tripmode"
cask "visual-studio-code"
cask "zoom"

# Mac App Store
mas "Amphetamine", id: 937984704
mas "Day One", id: 1055511498
mas "Keynote", id: 409183694
mas "iMovie", id: 408981434
mas "LINE", id: 539883307
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Paste", id: 967805235
mas "Prime Video", id: 545519333
mas "Todoist", id: 585829637

# Cursor Extensions
vscode "bierner.markdown-mermaid"
vscode "bpruitt-goddard.mermaid-markdown-syntax-highlighting"
vscode "dbaeumer.vscode-eslint"
vscode "esbenp.prettier-vscode"
vscode "graphql.vscode-graphql"
vscode "graphql.vscode-graphql-syntax"
vscode "ionutvmi.path-autocomplete"
vscode "kimuson.ts-type-expand"
vscode "marp-team.marp-vscode"
vscode "mohd-akram.vscode-html-format"
vscode "mquandalle.graphql"
vscode "ms-python.debugpy"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "ms-vsliveshare.vsliveshare"
vscode "nucllear.vscode-extension-auto-import"
vscode "oderwat.indent-rainbow"
vscode "openai.openai-chatgpt-adhoc"
vscode "orsenkucher.vscode-graphql"
vscode "prisma.prisma"
vscode "rooveterinaryinc.roo-cline"
vscode "saoudrizwan.claude-dev"
vscode "steoates.autoimport"
vscode "vscodevim.vim"
vscode "wix.vscode-import-cost"
vscode "yoavbls.pretty-ts-errors"
vscode "zenstack.zenstack"
