- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    homebrew_taps:
      - caskroom/cask
      - railwaycat/emacsmacport
      - sanemat/font
      - argon/mas
    homebrew_packages:
      - { name: heroku-toolbelt }
      - { name: openssl, state: linked, install_options: force }
      - { name: python }
      - { name: coreutils }
      - { name: docker-compose }
      - { name: git }
      - { name: wget }
      - { name: curl }
      - { name: cmake }
      - { name: autoconf }
      - { name: automake }
      - { name: pkg-config }
      - { name: ctags }
      - { name: tree }
      - { name: lv }
      - { name: mysql }
      - { name: nkf }
      - { name: nvm }
      - { name: jq }
      - { name: go }
      - { name: hub }
      - { name: redis }
      - { name: rbenv }
      - { name: ruby-build }
      - { name: tig }
      - { name: autojump }
      - { name: the_silver_searcher }
      - { name: vim }
      - { name: mas }
      - { name: zsh }
    mas_packages:
      # idはapp storeのアプリID
      - { name: deckset, id: 847496013 }
      - { name: moom , id: 419330170}
      - { name: reeder , id: 880001334 }
      - { name: tweetdeck, id: 485812721 }
      - { name: free-memory-pro, id: 460931672 }
      - { name: x-code, id: 497799835 }
    homebrew_cask_packages:
      - { name: alfred }
      - { name: alternote }
      - { name: appcleaner }
      - { name: apptivate }
      - { name: atom }
      - { name: bartender }
      - { name: clipy }
      - { name: dash }
      - { name: deckset }
      - { name: firefox }
      - { name: google-japanese-ime }
      - { name: gyazo }
      - { name: hyperswitch }
      - { name: intellij-idea }
      - { name: java }
      - { name: kindle }
      - { name: karabiner-elements }
      - { name: phpstorm }
      - { name: pomodone }
      - { name: pycharm }
      - { name: rescuetime }
      - { name: rubymine }
      - { name: slack }
      - { name: sequel-pro }
      - { name: skitch }
      - { name: the-unarchiver }
      - { name: visual-studio-code }

  tasks:
    - name: homebrew の tap リポジトリを追加
      homebrew_tap: tap={{ item }} state=present
      with_items: '{{ homebrew_taps }}'

    - name: homebrew をアップデート
      homebrew: update_homebrew=yes

    - name: brew パッケージをインストール
      homebrew: >
        name={{ item.name }}
        state={{ item.state | default('latest') }}
        install_options={{
          item.install_options | default() | join(',')
          if item.install_options is not string
          else item.install_options
        }}
      with_items: '{{ homebrew_packages }}'
      register: brew_result

    - name: cask パッケージをインストール
      homebrew_cask: name={{ item.name }} state={{ item.state|default('installed') }}
      with_items: '{{ homebrew_cask_packages }}'
      register: cask_result

    - name: App Storeのアプリをinstall
      command: mas install {{ item.id }}
      with_items: '{{ mas_packages }}'
      when: APP_STORE_ISNTALL == 'true'
