- hosts: localhost
  connection: local
  gather_facts: no           
  vars:
    homebrew_taps:
      - homebrew/binary
      - homebrew/dupes
      - caskroom/cask
      - railwaycat/emacsmacport
      - sanemat/font
    homebrew_packages:
      - { name: ansible }
      - { name: awscli }
      - { name: heroku-toolbelt }
      - { name: openssl }
      - { name: openssl, state: linked, install_options: force }
      - { name: python }
      - { name: coreutils }
      - { name: git }
      - { name: zsh, install_options: disable-etcdir }
      - { name: wget }
      - { name: curl }
      - { name: cmake }
      - { name: autoconf }
      - { name: automake }
      - { name: pkg-config }
      - { name: ctags }
      - { name: tree }
      - { name: lv }
      - { name: nkf }
      - { name: jq }
      - { name: go }
      - { name: direnv }
      - { name: peco }
      - { name: hub }
      - { name: tig }
      - { name: rbenv }
      - { name: ruby-build }
      - { name: mysql }
      - { name: sqlite }
      - { name: redis }
      - { name: imagemagick }
      - { name: packer }
      - { name: socat }
      - { name: tmux }
      - { name: reattach-to-user-namespace }
      - { name: phantomjs }
      - { name: autojump }
      - { name: gibo }
      - { name: source-highlight }
    homebrew_cask_packages:
      - { name: adobe-reader }
      - { name: alfred }
      - { name: appcleaner }
      - { name: apptivate }
      - { name: atom }
      - { name: bartender }
      - { name: caffeine }
      - { name: dash }
      - { name: dropbox }
      - { name: firefox }
      - { name: flux }
      - { name: google-chrome }
      - { name: iterm2 }
      - { name: intellij-idea }
      - { name: java }
      - { name: karabiner }
      - { name: kindle }
      - { name: moom }
      - { name: microsoft-office }
      - { name: phpstorm }
      - { name: pomodone }
      - { name: pophub }
      - { name: rescuetime }
      - { name: skype }
      - { name: slack }
      - { name: sourcetree }
      - { name: sequel-pro }
      - { name: skitch }
      - { name: vagrant }
      - { name: virtualbox }
      - { name: webstorm }

  tasks:
    - name: homebrew の tap リポジトリを追加
      homebrew_tap: tap={{ item }} state=present
      with_items: '{{ homebrew_taps }}'

    - name: homebrew をアップデート
      homebrew: update_homebrew=yes

    # brew
    - name: brew パッケージをインストール
      homebrew: >
        name={{ item.name }}
        state={{ item.state | default('latest') }}
        install_options={{
          item.install_options | default() | join(',')
          if item.install_options is not string
          else item.install_options
        }}
      with_items: '{{ homebrew_packages }}'
      register: brew_result
    - name: brew パッケージの情報保存先ディレクトリを作成
      file: path=brew_info state=directory
    #- name: brew パッケージの情報を保存
    #  shell: brew info {{ item }} > brew_info/{{ item }}
    #  with_items: brew_result.results | selectattr('changed') | map(attribute='item') | map(attribute='name') | list

    # cask
    - name: homebrew-cask のインストール
      homebrew: name=brew-cask state=latest
    - name: cask パッケージをインストール
      homebrew_cask: name={{ item.name }} state={{ item.state|default('installed') }}
      with_items: '{{ homebrew_cask_packages }}'
      register: cask_result
    - name: cask パッケージの情報保存先ディレクトリを作成
      file: path=cask_info state=directory
    #- name: cask パッケージの情報を保存
    #  shell: brew cask info {{ item }} > cask_info/{{ item }}
    #  with_items: cask_result.results | selectattr('changed') | map(attribute='item') | map(attribute='name') | list

    # Ricty
    - name: xquartz のインストール (for Ricty)
      homebrew_cask: name=xquartz
    - name: fontforge のインストール (for Ricty)
      homebrew: name=fontforge
    #- name: Ricty のインストール
    #  homebrew: name=ricty
    #- name: 生成されたフォントファイルをコピー
    #  shell: cp -f $(brew --cellar ricty)/*/share/fonts/Ricty*.ttf ~/Library/Fonts/
    #  args:
    #    creates: ~/Library/Fonts/Ricty-Bold.ttf
    #  notify: run fc-cache

  handlers:
    - name: run fc-cache
      shell: fc-cache -vf
