set encoding=utf-8
scriptencoding utf-8

"----------------------------------------------------------
" 基本設定
"----------------------------------------------------------
let mapleader = ","
set nobackup
set noswapfile
set autoread
set backspace=indent,eol,start
set visualbell t_vb=

noremap ,e :tabnew $MYVIMRC <CR>
noremap ,s :source $MYVIMRC <CR>
nnoremap ; :

"----------------------------------------------------------
" カラースキーム
"----------------------------------------------------------
syntax enable
set background=dark

"----------------------------------------------------------
" 文字
"----------------------------------------------------------
set fileencoding=utf-8
set fileencodings=ucs-boms,utf-8,euc-jp,cp932
set fileformats=unix,dos,mac
set ambiwidth=double

"----------------------------------------------------------
" ステータスライン
"----------------------------------------------------------
set laststatus=2
set showmode
set showcmd
set ruler

"----------------------------------------------------------
" タブ・インデント
"----------------------------------------------------------
set expandtab
set tabstop=4
set softtabstop=4
set autoindent
set smartindent
set shiftwidth=4

"----------------------------------------------------------
" 文字列検索
"----------------------------------------------------------
set incsearch
set ignorecase
set smartcase
set hlsearch

"----------------------------------------------------------
" カーソル
"----------------------------------------------------------
set whichwrap=b,s,h,l,<,>,[,],~
set number
set cursorline

nnoremap j gj
nnoremap k gk
nnoremap <down> gj
nnoremap <up> gk

" 前回終了したカーソル行に移動
if has("autocmd")
    autocmd BufReadPost *
        \ if line("'\"") > 0 && line ("'\"") <= line("$") |
        \   exe "normal! g'\"" |
        \ endif
endif

"----------------------------------------------------------
" カッコ・タグの対応
"----------------------------------------------------------
set showmatch
set wildmenu
set history=5000

"----------------------------------------------------------
" マウス
"----------------------------------------------------------
if has('mouse')
    set mouse=a
    if has('mouse_sgr')
        set ttymouse=sgr
    elseif v:version > 703 || v:version is 703 && has('patch632')
        set ttymouse=sgr
    else
        set ttymouse=xterm2
    endif
endif

"----------------------------------------------------------
" クリップボード
"----------------------------------------------------------
if &term =~ "xterm"
    let &t_SI .= "\e[?2004h"
    let &t_EI .= "\e[?2004l"
    let &pastetoggle = "\e[201~"

    function! XTermPasteBegin(ret)
        set paste
        return a:ret
    endfunction

    inoremap <special> <expr> <Esc>[200~ XTermPasteBegin("")
endif

"----------------------------------------------------------
" ローカル設定
"----------------------------------------------------------
if filereadable(expand('~/.vimrc.local'))
    source ~/.vimrc.local
endif
